# phenopath
![Overview](phenopath.svg)

## ERROR STATUS EXECUTION_ERROR

### ERROR CLUSTER EXECUTION_ERROR -- 1

 * Number of instances: 20
 * Dataset ids: scaling_0005, scaling_0014, scaling_0028, scaling_0049, scaling_0071, scaling_0100, scaling_0134, scaling_0175, scaling_0209, scaling_0250, scaling_0320, scaling_0381, scaling_0443, scaling_0496, scaling_0592, scaling_0665, scaling_0749, scaling_0838, scaling_0900, scaling_1037

Last 10 lines of scaling_0005:
```
File: /home/rcannood/Workspace/dynverse/dynbenchmark//derived/05-scaling/suite/phenopath/10/r2gridengine/20180825_051100_phenopath_10_6awIlP2ddJ/log/log.5.e.txt
Calls: lapply ... do.call -> <Anonymous> -> <Anonymous> -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/group/irc/shared/dynverse/dynbenchmark//derived/05-scaling/dataset/scaling_0005.rds', probable reason 'No such file or directory'
Execution halted
```

## ERROR STATUS TIME_LIMIT

### ERROR CLUSTER TIME_LIMIT -- 1

 * Number of instances: 23
 * Dataset ids: scaling_0867, scaling_0878, scaling_0951, scaling_0957, scaling_0959, scaling_0960, scaling_0963, scaling_0964, scaling_0975, scaling_0976, scaling_0981, scaling_0995, scaling_1000, scaling_1001, scaling_1002, scaling_1009, scaling_1010, scaling_1011, scaling_1023, scaling_1038, scaling_1039, scaling_1040, scaling_1041

Last 10 lines of scaling_0867:
```
File: /home/rcannood/Workspace/dynverse/dynbenchmark//derived/05-scaling/suite/phenopath/10/r2gridengine/20180825_051100_phenopath_10_6awIlP2ddJ/log/log.867.e.txt
```


